name: Build

on:
  workflow_dispatch:

jobs:
  build-win-x64:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
          
      - name: Publish
        run: dotnet publish -r win-x64 -c Release -o win-x64
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: win-x64
          path: win-x64/

  build-linux-x64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install dependencies
        run: sudo apt-get install -y libicu-dev libcurl4-openssl-dev zlib1g-dev libkrb5-dev

      - name: Publish
        run: dotnet publish -r linux-x64 -c Release -o linux-x64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: linux-x64/