name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Install dependencies
        run: sudo apt-get install -y libicu-dev libcurl4-openssl-dev zlib1g-dev libkrb5-dev

      - name: Publish
        run: dotnet publish -r linux-x64 -c Release -o linux-x64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: console-app
          path: linux-x64/